name: LG-UHC-S1
version: '${project.version}'
main: scriptservice.uhc.loupgarou.Main
load: STARTUP

commands:
  lg:
    description: la commande principale pour le loup-garou uhc.
  sethost:
    description: designe l'host de la game.
  cohost:
    description: la commande principale pour les co-host.